# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in htmlsnob_ruby.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"
gem "rb_sys", "~> 0.9.63"

gem "minitest", "~> 5.16"

gem "rubocop", "~> 1.21"

gem "toml-rb", "~> 4.1"
