# # Notes
# This is the default configuration file for HTML validation rules.
# 
# ## Warning Severity Usage
# - "error" for invalid HTML
# - "warning" for common best practices
# - "information" for the snobs strict HTML rules
# - "hint" Not used

# -------------------------------------------------------------------------------------------------------------------------------------------------------------
# -------------------- HEADER ---------------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------------------------------------------------------

template_language = "none"
indent_size = 2
max_line_length = 80

# -------------------------------------------------------------------------------------------------------------------------------------------------------------
# -------------------- ATTRIBUTES ---------------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------------------------------------------------------

# Unused: attribute_name_blacklist

[[rules]]
kind = "attribute_name_casing_style"
style = "kebab_case"
autofix = true

[[rules]]
kind = "attribute_name_missing"

# Unused: attribute_name_regexp

[[rules]]
kind = "attribute_name_requirement"
[rules.attributes]
html = ["lang"]
img = ["src", "alt"]
iframe = ["src"]
track = ["src"]
label = ["for"]
a = ["href"]
link = ["rel", "href"]
script = ["src"]

# Seperate file: attribute_name_whitelist

[[rules]]
kind = "attribute_value_casing_style"
autofix = true
style = "kebab_case"

[[rules]]
kind = "attribute_value_quote_style"
autofix = true
style = "double"

# Unused: attribute_value_regexp

[[rules]]
kind = "attribute_value_whitelist"
[rules.tag_attributes]
input.autocomplete = ["on", "off"]
select.autocomplete = ["on", "off"]
textarea.autocomplete = ["on", "off"]
dialog.closedby = ["any", "closerequest", "none"]
input.colorspace = ["limited-srgb", "display-p3"]
button.command = ["toggle-popover", "show-popover", "hide-popover", "close", "request-close", "show-modal", "--.+"]
form.enctype = ["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"]
audio.crossorigin = ["anonymous", "use-credentials", ""]
img.crossorigin = ["anonymous", "use-credentials", ""]
link.crossorigin = ["anonymous", "use-credentials", ""]
script.crossorigin = ["anonymous", "use-credentials", ""]
video.crossorigin = ["anonymous", "use-credentials", ""]
img.decoding = ["async", "sync", "auto"]
button.formmethod = ["get", "post", "dialog"]
input.formmethod = ["get", "post", "dialog"]
img.fetchpriority = ["high", "low", "auto"]
link.fetchpriority = ["high", "low", "auto"]
script.fetchpriority = ["high", "low", "auto"]
meta.http-equiv = ["content-type", "default-style", "refresh", "x-ua-compatible", "content-security-policy"]
track.kind = ["subtitles", "captions", "descriptions", "chapters", "metadata"]
iframe.loading = ["eager", "lazy"]
img.loading = ["eager", "lazy"]
form.method = ["get", "post", "dialog"]
button.popovertargetaction = ["show", "hide", "toggle"]
input.popovertargetaction = ["show", "hide", "toggle"]
audio.preload = ["none", "metadata", "auto", ""]
video.preload = ["none", "metadata", "auto", ""]
th.scope = ["row", "col", "rowgroup", "colgroup"]
area.shape = ["circle", "default", "poly", "rect"]
button.type = ["submit", "reset", "button"]
input.type = ["button", "checkbox", "color", "date", "datetime-local", "email", "file", "hidden", "image", "month", "number", "password", "radio", "range", "reset", "search", "submit", "tel", "text", "time", "url", "week"]
ol.type = ["1", "a", "A", "i", "I"]
textarea.wrap = ["soft", "hard"]
[rules.global_attributes]
autocapitalize = ["on", "off", "none", "sentences", "words", "characters"]
autocorrect = ["on", "off"]
contenteditable = ["true", "false", "plaintext-only", ""]
dir = ["ltr", "rtl", "auto"]
draggable = ["true", "false"]
enterkeyhint = ["enter", "done", "go", "next", "previous", "search", "send"]
hidden = ["until-found", "hidden", ""]
inputmode = ["none", "text", "tel", "url", "email", "numeric", "decimal", "search"]
popover = ["auto", "manual", "hint", ""]
spellcheck = ["true", "false", ""]
writingsuggestions = ["true", "false", ""]

[[rules]]
kind = "attributes_order"
order = ["class", "id", "name", "src", "for", "type", "href", "value", "title", "alt", "role"] # Same order as HtmlHint uses.

[[rules]]
kind = "boolean_attribute_style"
style = "no_value"
attributes = ["allowfullscreen", "alpha", "async", "autofocus", "autoplay", "checked", "controls", "default", "defer", "disabled", "formnovalidate", "inert", "ismap", "itemscope", "loop", "multiple", "muted", "nomodule", "novalidate", "open", "playsinline", "readonly", "required", "reversed", "selected", "shadowrootclonable", "shadowrootcustomelementregistry", "shadowrootdelegatesfocus", "shadowrootserializable"]

[[rules]]
kind = "duplicate_attribute_names_disallowed"

[[rules]]
kind = "class_name_casing_style"
case_style = "kebab_case"

# Seperate file: class_order

[[rules]]
kind = "duplicate_classes_disallowed"

[[rules]]
kind = "id_casing_style"
style = "kebab_case"
autofix = true

[[rules]]
kind = "id_unique"

[[rules]]
kind = "text_disallowed"
tags = ["address", "colgroup", "datalist", "dl", "figure", "head", "html", "map", "menu", "ol", "optgroup", "picture", "ruby", "search", "select", "table", "tbody", "template", "tfoot", "thead", "tr", "ul"]

# Unused: text_regexp

[[rules]]
kind = "text_requirement"
tags = ["abbr", "b", "cite", "code", "em", "h1", "h2", "h3", "h4", "h5", "h6", "i", "label", "mark", "p", "q", "small", "strong", "u"]


# TODO: All structure rules BELOW
[[rules]]
kind = "child_blacklist"
[rules.tags]
footer = ["header", "footer", ]
form = ["form", ]
header = ["header", "footer", ]

[[rules]]
kind = "descendant_blacklist"
[rules.tags]
a = ["a", ]
address = ["address", "article", "aside", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup", "nav", "section", ]
caption = ["table", ]
dfn = ["dfn", ]
dt = ["article", "aside", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup", "nav", "section", ]
label = ["label", ]
meter = ["meter", ]
noscript = ["noscript", ]
progress = ["progress", ]
th = ["article", "aside", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup", "nav", "section", ]

[[rules]]
kind = "content_model_categories"
[rules.tags]
a.categories = ["flow", "phrasing", ]
a.is_transparent = true
abbr.categories = ["flow", "phrasing", ]
abbr.child_category_whitelist = ["phrasing", ]
address.categories = ["flow", ]
address.child_category_whitelist = ["flow", ]
area.categories = ["flow", "phrasing", ]
area.child_category_whitelist = []
article.categories = ["flow", "sectioning", ]
article.child_category_whitelist = ["flow", "sectioning", ]
aside.categories = ["flow", "sectioning", ]
aside.child_category_whitelist = ["flow", ]
audio.categories = ["flow", "phrasing", ]
audio.is_special_case = true
b.categories = ["flow", "phrasing", ]
b.child_category_whitelist = ["phrasing", ]
base.categories = ["metadata", ]
base.child_category_whitelist = []
bdi.categories = ["flow", "phrasing", ]
bdi.child_category_whitelist = ["phrasing", ]
bdo.categories = ["flow", "phrasing", ]
bdo.child_category_whitelist = ["phrasing", ]
blockquote.categories = ["flow", ]
blockquote.child_category_whitelist = ["flow", ]
body.categories = []
body.child_category_whitelist = ["flow", ]
br.categories = ["flow", "phrasing", ]
br.child_category_whitelist = []
button.categories = ["flow", "phrasing", "interactive", ]
button.is_special_case = true
canvas.categories = ["flow", "phrasing", ]
canvas.is_transparent = true
canvas.child_tag_whitelist = ["a", "img", "button", "input", "select", ]
caption.categories = []
caption.child_category_whitelist = ["flow", ]
cite.categories = ["flow", "phrasing", ]
cite.child_category_whitelist = ["phrasing", ]
code.categories = ["flow", "phrasing", ]
code.child_category_whitelist = ["phrasing", ]
col.categories = []
col.child_category_whitelist = []
colgroup.categories = []
colgroup.is_special_case = true
data.categories = ["flow", "phrasing", ]
data.child_category_whitelist = ["phrasing", ]
datalist.categories = ["flow", "phrasing", ]
datalist.is_special_case = true
dd.categories = []
dd.child_category_whitelist = ["flow", ]
del.categories = []
del.child_category_whitelist = ["flow", ]
details.categories = ["flow", "interactive", ]
details.is_special_case = true
dfn.categories = ["flow", "phrasing", ]
dfn.child_category_whitelist = ["phrasing", ]
dialog.categories = ["flow", ]
dialog.child_category_whitelist = ["flow", ]
div.categories = ["flow", "palpable"]
div.child_category_whitelist = ["flow"]
div.child_tag_whitelist = ["dt", "dd"]
dl.categories = ["flow", ]
dl.is_special_case = true
dt.categories = []
dt.child_category_whitelist = ["flow", ]
em.categories = ["flow", "phrasing", ]
em.child_category_whitelist = ["phrasing", ]
embed.categories = ["flow", "phrasing", "interactive", ]
embed.child_category_whitelist = []
fencedframe.categories = ["flow", "phrasing", "interactive", ]
fencedframe.child_category_whitelist = []
fieldset.categories = ["flow", ]
fieldset.is_special_case = true
figcaption.categories = []
figcaption.child_category_whitelist = ["flow", ]
figure.categories = ["flow", ]
figure.is_special_case = true
footer.categories = ["flow", ]
footer.child_category_whitelist = ["flow", ]
form.categories = ["flow", ]
form.child_category_whitelist = ["flow", ]
h1.categories = ["flow", "heading", ]
h1.child_category_whitelist = ["phrasing", ]
h2.categories = ["flow", "heading", ]
h2.child_category_whitelist = ["phrasing", ]
h3.categories = ["flow", "heading", ]
h3.child_category_whitelist = ["phrasing", ]
h4.categories = ["flow", "heading", ]
h4.child_category_whitelist = ["phrasing", ]
h5.categories = ["flow", "heading", ]
h5.child_category_whitelist = ["phrasing", ]
h6.categories = ["flow", "heading", ]
h6.child_category_whitelist = ["phrasing", ]
head.categories = []
head.child_category_whitelist = ["metadata"]
header.categories = ["flow", ]
header.child_category_whitelist = ["flow", ]
hgroup.categories = ["flow", "heading", ]
hgroup.is_special_case = true
hr.categories = ["flow", ]
hr.child_category_whitelist = []
html.categories = []
html.child_category_whitelist = []
html.child_tag_whitelist = ["head", "body"]
i.categories = ["flow", "phrasing", ]
i.child_category_whitelist = ["phrasing", ]
iframe.categories = ["flow", "phrasing", "interactive", ]
iframe.child_category_whitelist = []
img.categories = ["flow", "phrasing", ]
img.child_category_whitelist = []
input.categories = ["flow", "phrasing", ]
input.child_category_whitelist = []
ins.categories = []
ins.child_category_whitelist = ["flow", ]
kbd.categories = ["flow", "phrasing", ]
kbd.child_category_whitelist = ["phrasing", ]
label.categories = ["flow", "phrasing", "interactive", ]
label.child_category_whitelist = ["phrasing", ]
legend.categories = []
legend.is_special_case = true
li.categories = []
li.child_category_whitelist = ["flow", ]
link.categories = ["metadata", ]
link.child_category_whitelist = []
main.categories = ["flow", ]
main.child_category_whitelist = ["flow", ]
map.categories = ["flow", "phrasing", ]
map.is_transparent = true
math.categories = ["flow", ]
math.child_category_whitelist = []
mark.categories = ["flow", "phrasing", ]
mark.child_category_whitelist = ["phrasing", ]
menu.categories = ["flow", ]
menu.child_category_whitelist = []
menu.child_tag_whitelist = ["li", "script", "template", ]
meta.categories = ["metadata", ]
meta.child_category_whitelist = []
meter.categories = ["flow", "phrasing", ]
meter.child_category_whitelist = ["phrasing", ]
nav.categories = ["flow", "sectioning", ]
nav.child_category_whitelist = ["flow", ]
noscript.categories = ["metadata", "flow", "phrasing", ]
noscript.is_transparent = true
object.categories = ["flow", "phrasing", ]
object.is_transparent = true
ol.categories = ["flow", ]
ol.child_category_whitelist = []
ol.child_tag_whitelist = ["li", "script", "template", ]
optgroup.categories = ["flow", "phrasing", ]
optgroup.is_special_case = true
option.categories = []
option.is_special_case = true
output.categories = ["flow", "phrasing", ]
output.child_category_whitelist = ["phrasing", ]
p.categories = ["flow", ]
p.child_category_whitelist = ["phrasing", ]
picture.categories = ["flow", "phrasing", ]
picture.is_special_case = true
pre.categories = ["flow", ]
pre.child_category_whitelist = ["phrasing", ]
progress.categories = ["flow", "phrasing", ]
progress.child_category_whitelist = ["phrasing", ]
q.categories = ["flow", "phrasing", ]
q.child_category_whitelist = ["phrasing", ]
rp.categories = []
rp.child_category_whitelist = []
rp.child_tag_whitelist = ["text", ]
rt.categories = []
rt.child_category_whitelist = ["phrasing", ]
ruby.categories = ["flow", "phrasing", ]
ruby.is_special_case = true
s.categories = ["flow", "phrasing", ]
s.child_category_whitelist = ["phrasing", ]
samp.categories = ["flow", "phrasing", ]
samp.child_category_whitelist = ["phrasing", ]
script.categories = ["metadata", "flow", "phrasing", ]
script.child_category_whitelist = ["text", ]
search.categories = ["flow", ]
search.child_category_whitelist = ["flow", ]
section.categories = ["flow", ]
section.child_category_whitelist = ["flow", ]
select.categories = ["flow", "phrasing", "interactive", ]
select.is_special_case = true
selectedcontent.categories = []
selectedcontent.child_category_whitelist = []
slot.categories = ["flow", "phrasing", ]
slot.is_transparent = true
small.categories = ["flow", "phrasing", ]
small.child_category_whitelist = ["phrasing", ]
source.categories = []
source.child_category_whitelist = []
span.categories = ["flow", "phrasing"]
span.child_category_whitelist = ["phrasing"]
span.child_tag_whitelist = ["dt", "dd"]
strong.categories = ["flow", "phrasing", ]
strong.child_category_whitelist = ["phrasing", ]
style.categories = ["metadata", ]
style.child_category_whitelist = ["text", ]
sub.categories = ["flow", "phrasing", ]
sub.child_category_whitelist = ["phrasing", ]
summary.categories = []
summary.child_category_whitelist = ["phrasing", ]
summary.child_tag_whitelist = ["h1", "h2", "h3", "h4", "h5", "h6", "hgroup", ]
sup.categories = ["flow", "phrasing", ]
sup.child_category_whitelist = ["phrasing", ]
svg.categories = ["flow", ]
svg.child_category_whitelist = []
table.categories = ["flow"]
table.child_category_whitelist = []
table.child_tag_whitelist = ["caption", "colgroup", "thead", "tbody", "tr", "tfoot"]]
tbody.categories = []
tbody.child_category_whitelist = []
tbody.child_tag_whitelist = ["tr", "script", "template", ]
td.categories = []
td.child_category_whitelist = ["flow", ]
template.categories = ["metadata", "flow", "phrasing", ]
template.is_special_case = true
textarea.categories = ["flow", "phrasing", "interactive", ]
textarea.child_category_whitelist = ["text", ]
tfoot.categories = []
tfoot.child_category_whitelist = []
tfoot.child_tag_whitelist = ["tr", "script", "template", ]
th.categories = []
th.child_category_whitelist = ["flow", ]
thead.categories = []
thead.child_category_whitelist = []
thead.child_tag_whitelist = ["tr", "script", "template", ]
time.categories = ["flow", "phrasing", ]
time.is_special_case = true
title.categories = ["metadata", ]
title.child_category_whitelist = ["text", ]
tr.categories = []
tr.child_category_whitelist = []
tr.child_tag_whitelist = ["td", "th", "script", "template", ]
track.categories = []
track.child_category_whitelist = []
track.child_tag_whitelist = ["td", "th", "script", "template", ]
u.categories = ["flow", "phrasing", ]
u.child_category_whitelist = ["phrasing", ]
ul.categories = ["flow", ]
ul.child_category_whitelist = []
ul.child_tag_whitelist = ["li", "script", "template", ]
var.categories = ["flow", "phrasing", ]
var.child_category_whitelist = ["phrasing", ]
video.categories = ["flow", "phrasing", ]
video.is_special_case = true
wbr.categories = ["flow", "phrasing", ]
wbr.child_category_whitelist = []

# TODO: All structure rules ABOVE

[[rules]]
kind = "missing_close_tag_disallowed"
except_tags = ["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"] # void elements

[[rules]]
kind = "missing_end_bracket_disallowed"

[[rules]]
kind = "missing_open_tag_disallowed"

[[rules]]
kind = "self_closing_tag_style"
style = "closed" 
tags = ["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"] # void elements

[[rules]]
error_message = "Tag `{name}` is deprecated."
kind = "tag_name_blacklist"
tags = ["applet", "acronym", "bgsound", "dir", "frame", "frameset", "noframes", "isindex", "keygen", "listing", "menuitem", "nextid", "noembed", "param", "plaintext", "rb", "rtc", "strike", "xmp", "basefont", "big", "blink", "center", "font", "marquee", "multicol", "nobr", "spacer", "tt"]

[[rules]]
kind = "tag_name_casing"
style = "lower"

[[rules]]
kind = "tag_name_regexp"
regexp = "^[A-Za-z][A-Za-z0-9.-]*$"

[[rules]]
kind = "tag_name_whitelist"
tags = ["a", "abbr", "address", "area", "article", "aside", "audio", "b", "base", "bdi", "bdo", "blockquote", "body", "br", "button", "canvas", "caption", "cite", "code", "col", "colgroup", "data", "datalist", "dd", "del", "details", "dfn", "dialog", "div", "dl", "dt", "em", "embed", "fencedframe", "fieldset", "figcaption", "figure", "footer", "form", "h1","h2","h3","h4","h5","h6", "head", "header", "hgroup", "hr", "html", "i", "iframe", "img", "input", "ins", "kbd", "label", "legend", "li", "link", "main", "map", "math", "mark", "menu", "meta", "meter", "nav", "noscript", "object", "ol", "optgroup", "option", "output", "p", "picture", "pre", "progress", "q", "rp", "rt", "ruby", "s", "samp", "script", "search", "section", "select", "selectedcontent", "slot", "small", "source", "span", "strong", "style", "sub", "summary", "sup", "svg", " table", "tbody", "td", "template", "textarea", "tfoot", "th", "thead", "time", "title", "tr", "track", "u", "ul", "var", "video", "wbr"]
